import type { EntityDef } from './types'

// ═══════════════════════════════════════════════════════════
// CONTENT DECLARATIONS
// All text content used by entities, declared here so it's
// easy to find and edit in one place.
// ═══════════════════════════════════════════════════════════

export const BRAND_NAME = 'Awshaf Ishtiaque'

export const TAGLINE = 'Web Dev Evolves, As Do I'

export const BIO_TEXT =
  "SFU grad. Startup founder. Instructor. I think in components and dream in keyframes. I have shipped React Native apps to both stores, taught 40 students how to build full-stack applications, and turned email chaos into order management systems. I find peace in a clean git history and purpose in a well-tested pipeline. Vancouver is home. The terminal is where I live."

export const CLOCK_HEADLINE = 'RESPECT THE CLOCK'

export const ALICE_QUOTE =
  'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, \u201cand what is the use of a book,\u201d thought Alice \u201cwithout pictures or conversations?\u201d'

export const HITCHHIKER_QUOTE =
  'In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.'

export const SPANISH_EXCERPT =
  'Muchos a\u00f1os despu\u00e9s, frente al pelot\u00f3n de fusilamiento, el coronel Aureliano Buend\u00eda hab\u00eda de recordar aquella tarde remota en que su padre lo llev\u00f3 a conocer el hielo.'

export const PULLQUOTE_BUTTON =
  '\u201cA button is never just a button. It is state management, accessibility, error handling, and the moment where the design changes after you have already shipped.\u201d'

export const PULLQUOTE_TIME =
  '\u201cEvery hour has a cost. The best teams do not treat developer time as free. They do not confuse presence with productivity.\u201d'

export const RESPECT_BODY =
  'Time is the only resource that does not scale. You cannot hire more of it. You cannot optimize it with a better algorithm. When someone wastes your time, they are spending something that neither of you can earn back.'

export const COMPONENTS_THOUGHT = 'I think in components\nand dream in keyframes'

// ═══════════════════════════════════════════════════════════
// ENTITY DEFINITIONS
// Each entity is a doodle/scribble on the notebook canvas.
// x, y are percentages of the 3000×3000px canvas.
// ═══════════════════════════════════════════════════════════

export const ENTITIES: EntityDef[] = [
  // ── Hero / Brand (center canvas) ──────────────────────
  {
    id: 'brand',
    x: 40,
    y: 44,
    rotate: -5,
    font: '"Permanent Marker", cursive',
    fontSize: '7.5rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.92,
    content: BRAND_NAME,
    type: 'text',
  },
  {
    id: 'tagline',
    x: 38,
    y: 51,
    rotate: 2,
    font: '"Caveat", cursive',
    fontSize: '3rem',
    fontWeight: '700',
    color: '#5a5245',
    opacity: 0.78,
    content: TAGLINE,
    type: 'text',
  },

  // ── Primary sections (scattered mid-canvas) ───────────
  {
    id: 'bio',
    x: 10,
    y: 32,
    rotate: -2,
    font: '"Patrick Hand", cursive',
    fontSize: '1.4rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.82,
    content: BIO_TEXT,
    maxWidth: 420,
    type: 'text',
  },
  {
    id: 'respect-clock',
    x: 58,
    y: 26,
    rotate: -6,
    font: '"Rock Salt", cursive',
    fontSize: '4rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    content: CLOCK_HEADLINE,
    type: 'text',
  },
  {
    id: 'clock-component',
    x: 72,
    y: 32,
    rotate: 3,
    font: 'system-ui',
    fontSize: '1rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 1,
    type: 'component',
    componentId: 'clock',
  },
  {
    id: 'three-component',
    x: 65,
    y: 58,
    rotate: -1,
    font: 'system-ui',
    fontSize: '1rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 1,
    type: 'component',
    componentId: 'three',
  },
  {
    id: 'respect-body',
    x: 55,
    y: 38,
    rotate: 1,
    font: '"Kalam", cursive',
    fontSize: '1.2rem',
    fontWeight: '300',
    color: '#5a554e',
    opacity: 0.68,
    content: RESPECT_BODY,
    maxWidth: 380,
    type: 'text',
  },

  // ── Secondary content (mid-edges) ─────────────────────
  {
    id: 'alice-quote',
    x: 10,
    y: 60,
    rotate: 4,
    font: '"Indie Flower", cursive',
    fontSize: '1.3rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.72,
    content: ALICE_QUOTE,
    maxWidth: 380,
    type: 'text',
  },
  {
    id: 'spanish-text',
    x: 48,
    y: 70,
    rotate: -3,
    font: '"Kalam", cursive',
    fontSize: '1.2rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.6,
    content: SPANISH_EXCERPT,
    maxWidth: 400,
    type: 'text',
  },
  {
    id: 'hitchhiker',
    x: 6,
    y: 80,
    rotate: 5,
    font: '"Caveat", cursive',
    fontSize: '1.5rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.7,
    content: HITCHHIKER_QUOTE,
    maxWidth: 450,
    type: 'text',
  },
  {
    id: 'pullquote-button',
    x: 52,
    y: 84,
    rotate: -4,
    font: '"Satisfy", cursive',
    fontSize: '1.35rem',
    fontWeight: '400',
    color: '#5a504a',
    opacity: 0.65,
    content: PULLQUOTE_BUTTON,
    maxWidth: 350,
    type: 'text',
  },
  {
    id: 'pullquote-time',
    x: 24,
    y: 86,
    rotate: 2,
    font: '"Shadows Into Light", cursive',
    fontSize: '1.3rem',
    fontWeight: '400',
    color: '#5a554e',
    opacity: 0.62,
    content: PULLQUOTE_TIME,
    maxWidth: 360,
    type: 'text',
  },
  {
    id: 'components-thought',
    x: 28,
    y: 52,
    rotate: -3,
    font: '"Satisfy", cursive',
    fontSize: '1.8rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.72,
    content: COMPONENTS_THOUGHT,
    type: 'text',
  },

  // ── Tags / Labels (corners, margins) ──────────────────
  {
    id: 'tag-react',
    x: 82,
    y: 10,
    rotate: 8,
    font: '"Permanent Marker", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#61dafb',
    opacity: 0.6,
    content: 'React',
    type: 'text',
  },
  {
    id: 'tag-ts',
    x: 86,
    y: 18,
    rotate: -10,
    font: '"Shadows Into Light", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#3178c6',
    opacity: 0.55,
    content: 'TypeScript',
    type: 'text',
  },
  {
    id: 'tag-threejs',
    x: 89,
    y: 40,
    rotate: 5,
    font: '"Architects Daughter", cursive',
    fontSize: '1.5rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.5,
    content: 'Three.js',
    type: 'text',
  },
  {
    id: 'tag-pretext',
    x: 5,
    y: 10,
    rotate: -7,
    font: '"Patrick Hand", cursive',
    fontSize: '1.4rem',
    fontWeight: '400',
    color: '#7a7570',
    opacity: 0.55,
    content: '@pretext',
    type: 'text',
  },
  {
    id: 'tag-a11y',
    x: 4,
    y: 42,
    rotate: 9,
    font: '"Rock Salt", cursive',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.52,
    content: 'a11y',
    type: 'text',
  },
  {
    id: 'tag-vancouver',
    x: 76,
    y: 88,
    rotate: -4,
    font: '"Indie Flower", cursive',
    fontSize: '1.4rem',
    fontWeight: '400',
    color: '#5a7a5a',
    opacity: 0.55,
    content: 'Vancouver, BC',
    type: 'text',
  },
  {
    id: 'tag-terminal',
    x: 3,
    y: 92,
    rotate: 2,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.3rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.5,
    content: '> terminal_',
    type: 'text',
  },
  {
    id: 'tag-framer',
    x: 88,
    y: 48,
    rotate: -6,
    font: '"Kalam", cursive',
    fontSize: '1.3rem',
    fontWeight: '400',
    color: '#8a5a8a',
    opacity: 0.48,
    content: 'framer-motion',
    type: 'text',
  },
  {
    id: 'tag-vite',
    x: 91,
    y: 58,
    rotate: 7,
    font: '"Caveat", cursive',
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#bd34fe',
    opacity: 0.5,
    content: 'Vite',
    type: 'text',
  },
  {
    id: 'tag-sfu',
    x: 14,
    y: 33,
    rotate: 6,
    font: '"Caveat", cursive',
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#cc0633',
    opacity: 0.55,
    content: "SFU '22",
    type: 'text',
  },
  {
    id: 'tag-git',
    x: 62,
    y: 46,
    rotate: 4,
    font: '"Patrick Hand", cursive',
    fontSize: '1.3rem',
    fontWeight: '400',
    color: '#f05032',
    opacity: 0.5,
    content: 'clean git history',
    type: 'text',
  },

  // ── Symbols / Decorators (far edges, sparse) ──────────
  {
    id: 'doodle-star',
    x: 93,
    y: 7,
    rotate: 15,
    font: 'system-ui',
    fontSize: '3rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.4,
    content: '\u2726',
    type: 'text',
  },
  {
    id: 'doodle-arrow',
    x: 33,
    y: 44,
    rotate: -8,
    font: 'system-ui',
    fontSize: '3.5rem',
    fontWeight: '400',
    color: '#8a8578',
    opacity: 0.35,
    content: '\u279c',
    type: 'text',
  },
  {
    id: 'doodle-squiggle',
    x: 22,
    y: 92,
    rotate: -3,
    font: 'system-ui',
    fontSize: '1.8rem',
    fontWeight: '400',
    color: '#9a9590',
    opacity: 0.3,
    content: '\u3030\u3030\u3030',
    type: 'text',
  },
  {
    id: 'doodle-hash',
    x: 94,
    y: 72,
    rotate: 12,
    font: '"Permanent Marker", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#aaa59e',
    opacity: 0.3,
    content: '###',
    type: 'text',
  },
  {
    id: 'page-number',
    x: 92,
    y: 95,
    rotate: 0,
    font: '"Patrick Hand", cursive',
    fontSize: '1.2rem',
    fontWeight: '400',
    color: '#8a8578',
    opacity: 0.45,
    content: 'pg. 1',
    type: 'text',
  },
  {
    id: 'date-stamp',
    x: 5,
    y: 96,
    rotate: -1,
    font: '"Architects Daughter", cursive',
    fontSize: '1.2rem',
    fontWeight: '400',
    color: '#8a8578',
    opacity: 0.45,
    content: 'April 2026',
    type: 'text',
  },
  {
    id: 'margin-note',
    x: 1.2,
    y: 55,
    rotate: -90,
    font: '"Patrick Hand", cursive',
    fontSize: '1.1rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.5,
    content: 'TODO: ship it',
    type: 'text',
  },
  {
    id: 'doodle-bracket',
    x: 7,
    y: 75,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '4rem',
    fontWeight: '400',
    color: '#9a9590',
    opacity: 0.25,
    content: '{',
    type: 'text',
  },
  {
    id: 'doodle-bracket-close',
    x: 35,
    y: 75,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '4rem',
    fontWeight: '400',
    color: '#9a9590',
    opacity: 0.25,
    content: '}',
    type: 'text',
  },
]
