import type { EntityDef } from './types'

// ═══════════════════════════════════════════════════════════
// CONTENT DECLARATIONS
// All text content used by entities, declared here so it's
// easy to find and edit in one place.
// ═══════════════════════════════════════════════════════════

export const BRAND_NAME = 'Awshaf Ishtiaque'

export const TAGLINE = 'Web Dev Evolves, As Do I'

export const BIO_TEXT =
  "SFU grad. Startup founder. Instructor. I think in components and dream in keyframes. I have shipped React Native apps to bo"

export const CLOCK_HEADLINE = 'RESPECT THE CLOCK'

export const ALICE_QUOTE =
  'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, \u201cand what is the use of a book,\u201d thought Alice \u201cwithout pictures or conversations?\u201d'

export const HITCHHIKER_QUOTE =
  'In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.'

export const SPANISH_EXCERPT =
  'Muchos a\u00f1os despu\u00e9s, frente al pelot\u00f3n de fusilamiento, el coronel Aureliano Buend\u00eda hab\u00eda de recordar aquella tarde remota en que su padre lo llev\u00f3 a conocer el hielo.'

export const PULLQUOTE_BUTTON =
  '\u201cA button is never just a button. It is state management, accessibility, error handling, and the moment where the design changes after you have already shipped.\u201d'

export const PULLQUOTE_TIME =
  '\u201cEvery hour has a cost. The best teams do not treat developer time as free. They do not confuse presence with productivity.\u201d'

export const RESPECT_BODY =
  'Time is the only resource that does not scale. You cannot hire more of it. You cannot optimize it with a better algorithm. When someone wastes your time, they are spending something that neither of you can earn back.'

export const COMPONENTS_THOUGHT = 'I think in components\nand dream in keyframes'

export const CODE_SNIPPET_1 = 'const life = () => code()'
export const CODE_SNIPPET_2 = '// TODO: take over the world'
export const CODE_SNIPPET_3 = 'git checkout -b dreams'
export const CODE_SNIPPET_4 = 'npm run dev'
export const CODE_SNIPPET_5 = '{ useState, useEffect, useRef }'
export const CODE_SNIPPET_6 = 'export default function App() {'
export const CODE_SNIPPET_7 = 'return <Canvas />'
export const CODE_SNIPPET_8 = 'import * as THREE from "three"'

export const GARCIA_2 =
  'El mundo era tan reciente, que muchas cosas carec\u00edan de nombre, y para mencionarlas hab\u00eda que se\u00f1alarlas con el dedo.'

export const HITCHHIKER_2 =
  'Many were increasingly of the opinion that they had all made a big mistake in coming down from the trees in the first place. And some said that even the trees had been a bad move.'

export const RESPECT_2 =
  'I learned to protect my time the hard way. By burning out. By delivering on impossible deadlines and being rewarded with more impossible deadlines. By saying yes until yes stopped meaning anything.'

export const CHECKLIST = '\u2610 tests\n\u2611 deploy\n\u2611 ship\n\u2610 sleep'

export const MEETING_NOTE =
  'I looked at my calendar and realized I had eight hours of meetings and was still expected to write code. Something had to give.'

// ═══════════════════════════════════════════════════════════
// ENTITY DEFINITIONS
// Each entity is a doodle/scribble on the notebook canvas.
// x, y are percentages of the 3000×3000px canvas.
// ═══════════════════════════════════════════════════════════

export const ENTITIES: EntityDef[] = [
  // ── Hero / Brand (center canvas) ──────────────────────
  {
    id: 'tagline',
    x: 38,
    y: 21,
    rotate: 2,
    font: '"Caveat", cursive',
    fontSize: '3.8rem',
    fontWeight: '700',
    color: '#3a3230',
    opacity: 0.78,
    content: TAGLINE,
    type: 'text',
  },

  // ── Primary sections (scattered mid-canvas) ───────────
  {
    id: 'bio',
    x: 8,
    y: 28,
    rotate: -2,
    font: '"Patrick Hand", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.82,
    content: BIO_TEXT,
    maxWidth: 545,
    type: 'text',
  },
  {
    id: 'respect-clock',
    x: 55,
    y: 22,
    rotate: -6,
    font: '"Rock Salt", cursive',
    fontSize: '5rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    content: CLOCK_HEADLINE,
    type: 'text',
  },

  // ── Secondary content (mid-edges) ─────────────────────
  {
    id: 'alice-quote',
    x: 70,
    y: 68,
    rotate: 4,
    font: '"Indie Flower", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.72,
    content: ALICE_QUOTE,
    maxWidth: 495,
    type: 'text',
  },
  {
    id: 'spanish-text',
    x: 8,
    y: 70,
    rotate: -3,
    font: '"Kalam", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.75,
    content: SPANISH_EXCERPT,
    maxWidth: 520,
    type: 'text',
  },
  {
    id: 'hitchhiker',
    x: 6,
    y: 82,
    rotate: 5,
    font: '"Caveat", cursive',
    fontSize: '2.1rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.7,
    content: HITCHHIKER_QUOTE,
    maxWidth: 585,
    type: 'text',
  },
  {
    id: 'pullquote-button',
    x: 42,
    y: 84,
    rotate: -4,
    font: '"Satisfy", cursive',
    fontSize: '1.35rem',
    fontWeight: '400',
    color: '#5a504a',
    opacity: 0.75,
    content: PULLQUOTE_BUTTON,
    maxWidth: 455,
    type: 'text',
  },
  {
    id: 'pullquote-time',
    x: 22,
    y: 92,
    rotate: 2,
    font: '"Shadows Into Light", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    content: PULLQUOTE_TIME,
    maxWidth: 470,
    type: 'text',
  },
  {
    id: 'components-thought',
    x: 20,
    y: 54,
    rotate: -3,
    font: '"Satisfy", cursive',
    fontSize: '2.6rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.72,
    content: COMPONENTS_THOUGHT,
    type: 'text',
  },

  // ── Tags / Labels (corners, margins) ──────────────────
  {
    id: 'tag-react',
    x: 82,
    y: 10,
    rotate: 8,
    font: '"Permanent Marker", cursive',
    fontSize: '2.8rem',
    fontWeight: '400',
    color: '#61dafb',
    opacity: 0.75,
    content: 'React',
    type: 'text',
  },
  {
    id: 'tag-ts',
    x: 93,
    y: 18,
    rotate: -10,
    font: '"Shadows Into Light", cursive',
    fontSize: '2.4rem',
    fontWeight: '400',
    color: '#3178c6',
    opacity: 0.7,
    content: 'TypeScript',
    type: 'text',
  },
  {
    id: 'tag-threejs',
    x: 90,
    y: 42,
    rotate: 5,
    font: '"Architects Daughter", cursive',
    fontSize: '2.1rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.6,
    content: 'Three.js',
    type: 'text',
  },
  {
    id: 'tag-pretext',
    x: 5,
    y: 10,
    rotate: -7,
    font: '"Patrick Hand", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.7,
    content: '@pretext',
    type: 'text',
  },
  {
    id: 'tag-a11y',
    x: 3,
    y: 38,
    rotate: 9,
    font: '"Rock Salt", cursive',
    fontSize: '2.3rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.7,
    content: 'a11y',
    type: 'text',
  },
  {
    id: 'tag-vancouver',
    x: 76,
    y: 94,
    rotate: -4,
    font: '"Indie Flower", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#5a7a5a',
    opacity: 0.7,
    content: 'Vancouver, BC',
    type: 'text',
  },
  {
    id: 'tag-terminal',
    x: 3,
    y: 96,
    rotate: 2,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.6,
    content: '> terminal_',
    type: 'text',
  },
  {
    id: 'tag-framer',
    x: 95,
    y: 52,
    rotate: -6,
    font: '"Kalam", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#8a5a8a',
    opacity: 0.6,
    content: 'framer-motion',
    type: 'text',
  },
  {
    id: 'tag-vite',
    x: 96,
    y: 62,
    rotate: 7,
    font: '"Caveat", cursive',
    fontSize: '2.1rem',
    fontWeight: '700',
    color: '#bd34fe',
    opacity: 0.6,
    content: 'Vite',
    type: 'text',
  },
  {
    id: 'tag-sfu',
    x: 16,
    y: 22,
    rotate: 6,
    font: '"Caveat", cursive',
    fontSize: '2.1rem',
    fontWeight: '700',
    color: '#cc0633',
    opacity: 0.7,
    content: "SFU '22",
    type: 'text',
  },
  {
    id: 'tag-git',
    x: 78,
    y: 44,
    rotate: 4,
    font: '"Patrick Hand", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#f05032',
    opacity: 0.6,
    content: 'clean git history',
    type: 'text',
  },


  // ── Fill: Top area (y 0–20%) ──────────────────────────
  {
    id: 'hello-world',
    x: 18,
    y: 4,
    rotate: 3,
    font: '"Permanent Marker", cursive',
    fontSize: '3.2rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.75,
    content: 'hello, world',
    type: 'text',
  },
  {
    id: 'html-tag',
    x: 30,
    y: 12,
    rotate: -4,
    font: '"JetBrains Mono", monospace',
    fontSize: '2.6rem',
    fontWeight: '400',
    color: '#e44d26',
    opacity: 0.6,
    content: '</>',
    type: 'text',
  },
  {
    id: 'code-snippet-1',
    x: 42,
    y: 8,
    rotate: 2,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.6,
    content: CODE_SNIPPET_1,
    type: 'text',
  },
  {
    id: 'todo-comment',
    x: 50,
    y: 3,
    rotate: -1,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.6,
    content: CODE_SNIPPET_2,
    type: 'text',
  },
  {
    id: 'dots-line',
    x: 48,
    y: 19,
    rotate: 0,
    font: 'system-ui',
    fontSize: '2.1rem',
    fontWeight: '400',
    color: '#7a7570',
    opacity: 0.45,
    content: '\u2022 \u2022 \u2022 \u2022 \u2022 \u2022 \u2022',
    type: 'text',
  },
  {
    id: 'use-state',
    x: 64,
    y: 3,
    rotate: 6,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#61dafb',
    opacity: 0.6,
    content: CODE_SNIPPET_5,
    type: 'text',
  },
  {
    id: 'npm-dev',
    x: 6,
    y: 18,
    rotate: -3,
    font: '"Patrick Hand", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#cb3837',
    opacity: 0.6,
    content: CODE_SNIPPET_4,
    type: 'text',
  },
  {
    id: 'circle-doodle',
    x: 38,
    y: 22,
    rotate: 0,
    font: 'system-ui',
    fontSize: '6rem',
    fontWeight: '400',
    color: '#b4afa5',
    opacity: 0.45,
    content: '\u25cb',
    type: 'text',
  },
  {
    id: 'asterisk-top',
    x: 3,
    y: 26,
    rotate: 10,
    font: '"Permanent Marker", cursive',
    fontSize: '3.8rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.45,
    content: '*',
    type: 'text',
  },

  // ── Fill: Mid-left (y 40–60%) ─────────────────────────
  {
    id: 'students-taught',
    x: 18,
    y: 44,
    rotate: 4,
    font: '"Indie Flower", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.7,
    content: '40 students taught',
    type: 'text',
  },
  {
    id: 'underline-1',
    x: 46,
    y: 70,
    rotate: -1,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.45,
    content: '_______________',
    type: 'text',
  },

  // ── Fill: Mid-right (y 45–65%) ────────────────────────
  {
    id: 'email-chaos',
    x: 50,
    y: 70,
    rotate: -2,
    font: '"Kalam", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.7,
    content: 'email chaos \u2192 order',
    type: 'text',
  },
  {
    id: 'shipped-stores',
    x: 82,
    y: 46,
    rotate: 5,
    font: '"Caveat", cursive',
    fontSize: '2.1rem',
    fontWeight: '700',
    color: '#3a3230',
    opacity: 0.7,
    content: 'shipped to both stores',
    type: 'text',
  },
  {
    id: 'arrow-down',
    x: 55,
    y: 70,
    rotate: 0,
    font: 'system-ui',
    fontSize: '3.2rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.45,
    content: '\u2193',
    type: 'text',
  },
  {
    id: 'app-function',
    x: 88,
    y: 50,
    rotate: -3,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#6a8a6a',
    opacity: 0.6,
    content: CODE_SNIPPET_6,
    type: 'text',
  },
  {
    id: 'return-canvas',
    x: 84,
    y: 58,
    rotate: -2,
    font: '"JetBrains Mono", monospace',
    fontSize: '0.95rem',
    fontWeight: '400',
    color: '#6a8a6a',
    opacity: 0.45,
    content: CODE_SNIPPET_7,
    type: 'text',
  },

  // ── Fill: Lower areas (y 65–80%) ──────────────────────
  {
    id: 'startup-note',
    x: 90,
    y: 72,
    rotate: -3,
    font: '"Rock Salt", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#5a504a',
    opacity: 0.6,
    content: 'startup founder',
    type: 'text',
  },
  {
    id: 'fullstack',
    x: 3,
    y: 62,
    rotate: 3,
    font: '"Permanent Marker", cursive',
    fontSize: '2.6rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.7,
    content: 'FULL STACK',
    type: 'text',
  },
  {
    id: 'instructor',
    x: 92,
    y: 78,
    rotate: -5,
    font: '"Satisfy", cursive',
    fontSize: '2.3rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.6,
    content: 'instructor',
    type: 'text',
  },
  {
    id: 'garcia-2',
    x: 10,
    y: 76,
    rotate: 2,
    font: '"Kalam", cursive',
    fontSize: '1.15rem',
    fontWeight: '300',
    color: '#5a5550',
    opacity: 0.6,
    content: GARCIA_2,
    maxWidth: 495,
    type: 'text',
  },
  {
    id: 'react-native',
    x: 90,
    y: 64,
    rotate: 7,
    font: '"Architects Daughter", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#61dafb',
    opacity: 0.6,
    content: 'React Native',
    type: 'text',
  },
  {
    id: 'hitchhiker-2',
    x: 10,
    y: 86,
    rotate: -2,
    font: '"Caveat", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.6,
    content: HITCHHIKER_2,
    maxWidth: 520,
    type: 'text',
  },
  {
    id: 'respect-2',
    x: 58,
    y: 96,
    rotate: 3,
    font: '"Indie Flower", cursive',
    fontSize: '1.15rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.7,
    content: RESPECT_2,
    maxWidth: 495,
    type: 'text',
  },
  {
    id: 'git-branch',
    x: 84,
    y: 98,
    rotate: 3,
    font: '"JetBrains Mono", monospace',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#f05032',
    opacity: 0.6,
    content: CODE_SNIPPET_3,
    type: 'text',
  },
  {
    id: 'three-import',
    x: 62,
    y: 44,
    rotate: -1,
    font: '"JetBrains Mono", monospace',
    fontSize: '0.95rem',
    fontWeight: '400',
    color: '#7a7a9a',
    opacity: 0.45,
    content: CODE_SNIPPET_8,
    type: 'text',
  },
  {
    id: 'checklist',
    x: 14,
    y: 96,
    rotate: -2,
    font: '"Patrick Hand", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#5a8a5a',
    opacity: 0.6,
    content: CHECKLIST,
    type: 'text',
  },
  {
    id: 'meeting-note',
    x: 35,
    y: 96,
    rotate: 1,
    font: '"Shadows Into Light", cursive',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#4a4540',
    opacity: 0.6,
    content: MEETING_NOTE,
    maxWidth: 440,
    type: 'text',
  },

  // ── Fill: Right edge (x 85–98%) ───────────────────────
  {
    id: 'doodle-line-v',
    x: 98,
    y: 22,
    rotate: 0,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.45,
    content: '|\n|\n|\n|\n|',
    type: 'text',
  },
  {
    id: 'tag-css',
    x: 92,
    y: 35,
    rotate: -8,
    font: '"Permanent Marker", cursive',
    fontSize: '2rem',
    fontWeight: '400',
    color: '#264de4',
    opacity: 0.6,
    content: 'CSS',
    type: 'text',
  },
  {
    id: 'tag-node',
    x: 98,
    y: 70,
    rotate: 4,
    font: '"Architects Daughter", cursive',
    fontSize: '1.9rem',
    fontWeight: '400',
    color: '#68a063',
    opacity: 0.6,
    content: 'Node.js',
    type: 'text',
  },
  {
    id: 'tag-webgl',
    x: 92,
    y: 85,
    rotate: -5,
    font: '"Rock Salt", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.6,
    content: 'WebGL',
    type: 'text',
  },
  {
    id: 'doodle-x',
    x: 97,
    y: 44,
    rotate: 15,
    font: '"Permanent Marker", cursive',
    fontSize: '3.2rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.45,
    content: '\u00d7',
    type: 'text',
  },

  // ── Fill: Left edge (x 1–8%) ──────────────────────────
  {
    id: 'margin-note-2',
    x: 1.5,
    y: 68,
    rotate: -90,
    font: '"Patrick Hand", cursive',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.6,
    content: 'note to self',
    type: 'text',
  },
  {
    id: 'margin-note-3',
    x: 1.8,
    y: 30,
    rotate: -90,
    font: '"Patrick Hand", cursive',
    fontSize: '0.95rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.45,
    content: 'refactor later',
    type: 'text',
  },
  {
    id: 'doodle-star-left',
    x: 2,
    y: 76,
    rotate: 20,
    font: 'system-ui',
    fontSize: '2.8rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.45,
    content: '\u2605',
    type: 'text',
  },

  // ── Fill: Bottom corners ──────────────────────────────
  {
    id: 'end-bracket',
    x: 98,
    y: 90,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '3.8rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.45,
    content: '};',
    type: 'text',
  },
  {
    id: 'dots-bottom',
    x: 45,
    y: 97,
    rotate: 0,
    font: 'system-ui',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#7a7570',
    opacity: 0.45,
    content: '\u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7 \u00b7',
    type: 'text',
  },

  // ── Symbols / Decorators (far edges, sparse) ──────────
  {
    id: 'doodle-star',
    x: 93,
    y: 7,
    rotate: 15,
    font: 'system-ui',
    fontSize: '3.8rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.6,
    content: '\u2726',
    type: 'text',
  },
  {
    id: 'doodle-arrow',
    x: 16,
    y: 40,
    rotate: -8,
    font: 'system-ui',
    fontSize: '4.2rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.45,
    content: '\u279c',
    type: 'text',
  },
  {
    id: 'doodle-squiggle',
    x: 30,
    y: 94,
    rotate: -3,
    font: 'system-ui',
    fontSize: '2.6rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.45,
    content: '\u3030\u3030\u3030',
    type: 'text',
  },
  {
    id: 'doodle-hash',
    x: 98,
    y: 80,
    rotate: 12,
    font: '"Permanent Marker", cursive',
    fontSize: '2.8rem',
    fontWeight: '400',
    color: '#7a7570',
    opacity: 0.45,
    content: '###',
    type: 'text',
  },
  {
    id: 'page-number',
    x: 92,
    y: 95,
    rotate: 0,
    font: '"Patrick Hand", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.6,
    content: 'pg. 1',
    type: 'text',
  },
  {
    id: 'date-stamp',
    x: 8,
    y: 98,
    rotate: -1,
    font: '"Architects Daughter", cursive',
    fontSize: '1.7rem',
    fontWeight: '400',
    color: '#5a5550',
    opacity: 0.6,
    content: 'April 2026',
    type: 'text',
  },
  {
    id: 'margin-note',
    x: 1.2,
    y: 54,
    rotate: -90,
    font: '"Patrick Hand", cursive',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.6,
    content: 'TODO: ship it',
    type: 'text',
  },
  {
    id: 'doodle-bracket',
    x: 7,
    y: 56,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '5rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.45,
    content: '{',
    type: 'text',
  },
  {
    id: 'doodle-bracket-close',
    x: 14,
    y: 56,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '5rem',
    fontWeight: '400',
    color: '#6a6560',
    opacity: 0.45,
    content: '}',
    type: 'text',
  },

  // ═══════════════════════════════════════════════════════
  // RED OBSTACLES — drag these over text to see it reflow
  // ═══════════════════════════════════════════════════════
  {
    id: 'obs-deadline',
    x: 18,
    y: 30,
    rotate: 0,
    font: '"Permanent Marker", cursive',
    fontSize: '3.2rem',
    fontWeight: '400',
    color: '#c83030',
    opacity: 0.9,
    content: 'deadline',
    type: 'text',
    obstacle: true,
    obstacleW: 275,
    obstacleH: 58,
  },
  {
    id: 'obs-asap',
    x: 82,
    y: 72,
    rotate: 0,
    font: '"Rock Salt", cursive',
    fontSize: '2.8rem',
    fontWeight: '400',
    color: '#c83030',
    opacity: 0.9,
    content: 'ASAP',
    type: 'text',
    obstacle: true,
    obstacleW: 195,
    obstacleH: 55,
  },
  {
    id: 'obs-scope-creep',
    x: 14,
    y: 78,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '3rem',
    fontWeight: '700',
    color: '#c83030',
    opacity: 0.9,
    content: 'scope creep',
    type: 'text',
    obstacle: true,
    obstacleW: 260,
    obstacleH: 52,
  },
  {
    id: 'obs-quick-call',
    x: 55,
    y: 72,
    rotate: 0,
    font: '"Patrick Hand", cursive',
    fontSize: '2.8rem',
    fontWeight: '400',
    color: '#c83030',
    opacity: 0.9,
    content: 'quick call',
    type: 'text',
    obstacle: true,
    obstacleW: 220,
    obstacleH: 50,
  },
  {
    id: 'obs-one-more-thing',
    x: 40,
    y: 85,
    rotate: 0,
    font: '"Indie Flower", cursive',
    fontSize: '2.6rem',
    fontWeight: '400',
    color: '#c83030',
    opacity: 0.9,
    content: 'one more thing',
    type: 'text',
    obstacle: true,
    obstacleW: 290,
    obstacleH: 48,
  },

  // ═══════════════════════════════════════════════════════
  // BOLD / DARK / LARGER DOODLES — punchy contrast pieces
  // ═══════════════════════════════════════════════════════
  {
    id: 'bold-debug',
    x: 72,
    y: 6,
    rotate: -4,
    font: '"Permanent Marker", cursive',
    fontSize: '5.5rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.88,
    content: 'DEBUG',
    type: 'text',
  },
  {
    id: 'bold-deploy',
    x: 6,
    y: 46,
    rotate: 3,
    font: '"Rock Salt", cursive',
    fontSize: '4.2rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.82,
    content: 'DEPLOY',
    type: 'text',
  },
  {
    id: 'bold-iterate',
    x: 50,
    y: 88,
    rotate: -6,
    font: '"Permanent Marker", cursive',
    fontSize: '6rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.85,
    content: 'ITERATE',
    type: 'text',
  },
  {
    id: 'bold-question',
    x: 92,
    y: 28,
    rotate: 12,
    font: '"Caveat", cursive',
    fontSize: '7rem',
    fontWeight: '700',
    color: '#2a2520',
    opacity: 0.7,
    content: '?',
    type: 'text',
  },
  {
    id: 'bold-exclaim',
    x: 2,
    y: 90,
    rotate: -8,
    font: '"Caveat", cursive',
    fontSize: '8rem',
    fontWeight: '700',
    color: '#3a3530',
    opacity: 0.75,
    content: '!',
    type: 'text',
  },
  {
    id: 'bold-arrow-right',
    x: 16,
    y: 32,
    rotate: 2,
    font: 'system-ui',
    fontSize: '6rem',
    fontWeight: '700',
    color: '#2a2520',
    opacity: 0.75,
    content: '\u2794',
    type: 'text',
  },
  {
    id: 'bold-learn',
    x: 68,
    y: 94,
    rotate: 5,
    font: '"Rock Salt", cursive',
    fontSize: '4.5rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.78,
    content: 'LEARN',
    type: 'text',
  },
  {
    id: 'bold-repeat',
    x: 82,
    y: 64,
    rotate: -3,
    font: '"Permanent Marker", cursive',
    fontSize: '4rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.75,
    content: 'REPEAT.',
    type: 'text',
  },
  {
    id: 'bold-star-dark',
    x: 56,
    y: 12,
    rotate: 18,
    font: 'system-ui',
    fontSize: '6rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.6,
    content: '\u2605',
    type: 'text',
  },
  {
    id: 'bold-hashtag',
    x: 14,
    y: 12,
    rotate: -6,
    font: '"Permanent Marker", cursive',
    fontSize: '5rem',
    fontWeight: '400',
    color: '#2a2520',
    opacity: 0.75,
    content: '#MVP',
    type: 'text',
  },
  {
    id: 'bold-xmark',
    x: 86,
    y: 92,
    rotate: 10,
    font: '"Caveat", cursive',
    fontSize: '7rem',
    fontWeight: '700',
    color: '#c85a5a',
    opacity: 0.7,
    content: '\u2717',
    type: 'text',
  },
  {
    id: 'bold-check',
    x: 82,
    y: 38,
    rotate: -5,
    font: 'system-ui',
    fontSize: '6.5rem',
    fontWeight: '700',
    color: '#3a6a3a',
    opacity: 0.6,
    content: '\u2713',
    type: 'text',
  },

  // ═══════════════════════════════════════════════════════
  // DOODLE IMAGES — sketched logos/icons on the notebook
  // ═══════════════════════════════════════════════════════

  // Draggable doodles
  {
    id: 'doodle-lightbulb',
    x: 6,
    y: 14,
    rotate: 8,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.7,
    type: 'text',
    imgSrc: '/doodles/lightbulb.svg',
    imgW: 77,
    imgH: 102,
  },
  {
    id: 'doodle-coffee',
    x: 80,
    y: 18,
    rotate: -6,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    type: 'text',
    imgSrc: '/doodles/coffee.svg',
    imgW: 86,
    imgH: 80,
  },
  {
    id: 'doodle-rocket',
    x: 22,
    y: 70,
    rotate: 12,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    type: 'text',
    imgSrc: '/doodles/rocket.svg',
    imgW: 67,
    imgH: 96,
  },
  {
    id: 'doodle-speech',
    x: 76,
    y: 68,
    rotate: -4,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.7,
    type: 'text',
    imgSrc: '/doodles/speech.svg',
    imgW: 90,
    imgH: 74,
  },

  // Obstacle doodle — text reflows around it
  {
    id: 'doodle-heart-obs',
    x: 50,
    y: 75,
    rotate: 5,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c85a5a',
    opacity: 0.8,
    type: 'text',
    imgSrc: '/doodles/heart.svg',
    imgW: 83,
    imgH: 77,
    obstacle: true,
    obstacleW: 64,
    obstacleH: 59,
  },

  // Fixed doodles (can't be moved, collision zone)
  {
    id: 'doodle-code-fixed',
    x: 18,
    y: 22,
    rotate: -3,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#3a3530',
    opacity: 0.75,
    type: 'text',
    imgSrc: '/doodles/code.svg',
    imgW: 93,
    imgH: 67,
  },
  {
    id: 'doodle-star-fixed',
    x: 92,
    y: 28,
    rotate: 10,
    font: 'system-ui',
    fontSize: '1.6rem',
    fontWeight: '400',
    color: '#c8b882',
    opacity: 0.75,
    type: 'text',
    imgSrc: '/doodles/star.svg',
    imgW: 80,
    imgH: 77,
  },

  // ═══════════════════════════════════════════════════════
  // LARGE BACKGROUND ENTITIES — visible when zoomed out
  // These serve as background texture / watermarks
  // ═══════════════════════════════════════════════════════
  {
    id: 'bg-code',
    x: 25,
    y: 20,
    rotate: -12,
    font: '"Permanent Marker", cursive',
    fontSize: '18rem',
    fontWeight: '400',
    color: '#d5d0c8',
    opacity: 0.18,
    content: 'CODE',
    type: 'text',
  },
  {
    id: 'bg-build',
    x: 55,
    y: 70,
    rotate: 8,
    font: '"Caveat", cursive',
    fontSize: '14rem',
    fontWeight: '700',
    color: '#d5d0c8',
    opacity: 0.14,
    content: 'BUILD',
    type: 'text',
  },
  {
    id: 'bg-ship',
    x: 10,
    y: 78,
    rotate: -5,
    font: '"Rock Salt", cursive',
    fontSize: '12rem',
    fontWeight: '400',
    color: '#d8d3cb',
    opacity: 0.12,
    content: 'SHIP',
    type: 'text',
  },
  {
    id: 'bg-dream',
    x: 65,
    y: 15,
    rotate: 6,
    font: '"Satisfy", cursive',
    fontSize: '10rem',
    fontWeight: '400',
    color: '#d5d0c8',
    opacity: 0.13,
    content: 'dream',
    type: 'text',
  },
  {
    id: 'bg-circle-large',
    x: 70,
    y: 40,
    rotate: 0,
    font: 'system-ui',
    fontSize: '25rem',
    fontWeight: '100',
    color: '#ccc8c0',
    opacity: 0.1,
    content: '\u25cb',
    type: 'text',
  },
  {
    id: 'bg-ampersand',
    x: 5,
    y: 42,
    rotate: -15,
    font: '"Caveat", cursive',
    fontSize: '20rem',
    fontWeight: '700',
    color: '#d5d0c8',
    opacity: 0.1,
    content: '&',
    type: 'text',
  },
  {
    id: 'bg-slash',
    x: 82,
    y: 55,
    rotate: 10,
    font: '"JetBrains Mono", monospace',
    fontSize: '16rem',
    fontWeight: '400',
    color: '#d5d0c8',
    opacity: 0.08,
    content: '//',
    type: 'text',
  },
  {
    id: 'bg-arrow-long',
    x: 15,
    y: 92,
    rotate: -2,
    font: 'system-ui',
    fontSize: '8rem',
    fontWeight: '400',
    color: '#ccc8c0',
    opacity: 0.15,
    content: '\u2192 \u2192 \u2192 \u2192 \u2192',
    type: 'text',
  },
  {
    id: 'bg-web',
    x: 40,
    y: 2,
    rotate: 3,
    font: '"Permanent Marker", cursive',
    fontSize: '12rem',
    fontWeight: '400',
    color: '#d8d3cb',
    opacity: 0.12,
    content: 'WEB',
    type: 'text',
  },
  {
    id: 'bg-curly-open',
    x: 2,
    y: 5,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '22rem',
    fontWeight: '400',
    color: '#d5d0c8',
    opacity: 0.08,
    content: '{',
    type: 'text',
  },
  {
    id: 'bg-curly-close',
    x: 85,
    y: 82,
    rotate: 0,
    font: '"Caveat", cursive',
    fontSize: '22rem',
    fontWeight: '400',
    color: '#d5d0c8',
    opacity: 0.08,
    content: '}',
    type: 'text',
  },
]
